# Generated by Django 3.1.6 on 2021-05-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0002_product_raw_demand_raw_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bata_plant',
            old_name='first_nam',
            new_name='first_name',
        ),
    ]
