# Generated by Django 3.1.6 on 2021-05-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0004_raw_product_material_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_demand',
            name='Raw_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bata.raw_product'),
        ),
    ]
