# Generated by Django 3.1.6 on 2021-05-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0006_auto_20210526_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='bata_plant',
            name='location',
            field=models.CharField(default='Select', max_length=100),
        ),
    ]
