# Generated by Django 3.2.4 on 2021-07-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Polyurethane', models.IntegerField(default=None, max_length=50)),
                ('Rubber', models.IntegerField(default=None, max_length=50)),
                ('Dye', models.IntegerField(default=None, max_length=50)),
                ('Packaging_Material', models.IntegerField(default=None, max_length=50)),
                ('GUM', models.IntegerField(default=None, max_length=50)),
                ('PVC_Sole', models.IntegerField(default=None, max_length=50)),
                ('TPR', models.IntegerField(default=None, max_length=50)),
                ('Hard_Thread', models.IntegerField(default=None, max_length=50)),
                ('Rexene', models.IntegerField(default=None, max_length=50)),
                ('Clips', models.IntegerField(default=None, max_length=50)),
                ('Color', models.IntegerField(default=None, max_length=50)),
                ('Price', models.IntegerField(default=None, max_length=50)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bata.product')),
                ('raw_product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bata.raw_product')),
            ],
            options={
                'db_table': 'RawMaterial_categories',
            },
        ),
    ]
