# Generated by Django 3.1.6 on 2021-05-25 08:06

import bata.model.Raw_demand
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bata.bata_plant')),
            ],
            options={
                'db_table': 'RawMaterial_Product',
            },
        ),
        migrations.CreateModel(
            name='Raw_Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lot_number', models.CharField(max_length=30)),
                ('Raw_type', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(default=0)),
                ('Demand_date', models.DateField(default=datetime.date.today)),
                ('Requirement_date', models.DateField(default=bata.model.Raw_demand.return_date_time)),
                ('user_location', models.CharField(max_length=40)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bata.bata_plant')),
            ],
            options={
                'db_table': 'RawMaterial_Demand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bata.bata_plant')),
            ],
            options={
                'db_table': 'Plant_Product',
            },
        ),
    ]
