# Generated by Django 3.2.4 on 2021-07-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='raw_demand',
            table='Raw_Material_Demand',
        ),
    ]
