# Generated by Django 3.2.4 on 2021-07-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0002_raw_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_product_category',
            old_name='Price',
            new_name='Price_Clips',
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_Color',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_Dye',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_GUM',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_Hard_Thread',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_PVC_Sole',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_Packaging_Material',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_Polyurethane',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_Rexene',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_Rubber',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='raw_product_category',
            name='Price_TPR',
            field=models.IntegerField(default=None, max_length=50),
        ),
    ]
