# Generated by Django 3.2.4 on 2021-07-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0002_alter_raw_demand_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_demand',
            name='Raw_type',
        ),
    ]
