# Generated by Django 3.2.4 on 2021-07-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0003_auto_20210706_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_product_category',
            name='raw_product',
        ),
    ]
