# Generated by Django 3.1.6 on 2021-05-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0003_auto_20210525_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_product',
            name='Material_id',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
