# Generated by Django 3.2.4 on 2021-07-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0003_remove_raw_demand_raw_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_demand',
            name='Price',
            field=models.FloatField(default=None, max_length=50),
        ),
    ]
