# Generated by Django 3.2.4 on 2021-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0004_remove_raw_product_category_raw_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_product_category',
            name='Clips',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Color',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Dye',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='GUM',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Hard_Thread',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='PVC_Sole',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Packaging_Material',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Polyurethane',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_Clips',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_Color',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_Dye',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_GUM',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_Hard_Thread',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_PVC_Sole',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_Packaging_Material',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_Polyurethane',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_Rexene',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_Rubber',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Price_TPR',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Rexene',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='Rubber',
            field=models.FloatField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_product_category',
            name='TPR',
            field=models.FloatField(default=None, max_length=50),
        ),
    ]
