# Generated by Django 3.2.4 on 2021-07-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0008_auto_20210707_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_demand',
            name='Clips',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Color',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Dye',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='GUM',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Hard_Thread',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='PVC_Sole',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Packaging_Material',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Polyurethane',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Price',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Rexene',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Rubber',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='TPR',
            field=models.FloatField(default=0, max_length=50, null=True),
        ),
    ]
