# Generated by Django 3.2.4 on 2021-07-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0009_auto_20210707_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_demand',
            name='GUM',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Polyurethane',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Price',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Rubber',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
