# Generated by Django 3.2.4 on 2021-07-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0010_auto_20210707_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_demand',
            name='Clips',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Color',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Dye',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Hard_Thread',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='PVC_Sole',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Packaging_Material',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='Rexene',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='TPR',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
