# Generated by Django 3.2.4 on 2021-06-11 04:26

import bata.model.Raw_demand
import bata.model.seller_demand
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BATA_PLANT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('location', models.CharField(default='Select', max_length=100)),
            ],
            options={
                'db_table': 'BATA_PLANT_LOGIN',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('location', models.CharField(default='Select', max_length=100)),
            ],
            options={
                'db_table': 'Distributor_Login',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bata.bata_plant')),
            ],
            options={
                'db_table': 'Plant_Product',
            },
        ),
        migrations.CreateModel(
            name='Quality_checking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('location', models.CharField(default='Select', max_length=100)),
            ],
            options={
                'db_table': 'Quality_checking_LOGIN',
            },
        ),
        migrations.CreateModel(
            name='Raw_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Material_id', models.CharField(default='none', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bata.bata_plant')),
            ],
            options={
                'db_table': 'RawMaterial_Product',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('location', models.CharField(default='Select', max_length=100)),
            ],
            options={
                'db_table': 'Seller_Login',
            },
        ),
        migrations.CreateModel(
            name='Seller_demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Demand_date', models.DateField(default=datetime.date.today)),
                ('Requirement_date', models.DateField(default=bata.model.seller_demand.return_date_time)),
                ('user_location', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DISPATCHED', 'DISPATCHED'), ('RECEIVED', 'RECEIVED')], default='PENDING', max_length=20)),
                ('product', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='bata.product')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bata.seller')),
            ],
            options={
                'db_table': 'Seller_demand',
            },
        ),
        migrations.CreateModel(
            name='RM_provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('location', models.CharField(default='Select', max_length=100)),
                ('Raw_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bata.raw_product')),
            ],
            options={
                'db_table': 'RM_provider_Login',
            },
        ),
        migrations.CreateModel(
            name='Raw_Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lot_number', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField(default=0)),
                ('Demand_date', models.DateField(default=datetime.date.today)),
                ('Requirement_date', models.DateField(default=bata.model.Raw_demand.return_date_time)),
                ('user_location', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DISPATCHED', 'DISPATCHED'), ('RECEIVED', 'RECEIVED')], default='PENDING', max_length=20)),
                ('Raw_type', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='bata.raw_product')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bata.bata_plant')),
            ],
            options={
                'db_table': 'RawMaterial_Demand',
            },
        ),
        migrations.CreateModel(
            name='Cheking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok_pcs', models.IntegerField(default=0)),
                ('Defected_pcs', models.IntegerField(default=0)),
                ('Lot_number', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bata.raw_demand')),
                ('Qualitycheck_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bata.quality_checking')),
                ('plant_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bata.bata_plant')),
            ],
            options={
                'db_table': 'Product_Checking',
            },
        ),
    ]
