# Generated by Django 3.2.4 on 2021-06-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_demand',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bata.bata_plant'),
        ),
    ]
