# Generated by Django 3.2.4 on 2021-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0002_alter_raw_demand_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bata_plant',
            name='location',
            field=models.CharField(choices=[('MUMBAI', 'PENDING'), ('DELHI', 'DELHI'), ('PUNE', 'PUNE'), ('GOA', 'GOA')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='raw_demand',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DISPATCHED', 'DISPATCHED')], default='PENDING', max_length=20),
        ),
    ]
