# Generated by Django 3.1.6 on 2021-05-26 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0005_auto_20210526_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_demand',
            name='Raw_type',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='bata.raw_product'),
        ),
    ]
