# Generated by Django 3.1.6 on 2021-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata', '0007_bata_plant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_demand',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DISPATCHED', 'DISPATCHED'), ('RECEIVED', 'RECEIVED')], default='PENDING', max_length=20),
        ),
    ]
